Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)


In [1]:
import numpy as np

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [4]:
list_ =  [ '1' , '2', '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [8]:
print(type(list_[0]))
print(type(array_list[0]))

<class 'str'>
<class 'numpy.str_'>


The main difference between str and numpy.str_ is str is built in data type in python where as numpy.str_ is a specific data type provided by numpy library. numpy.str_ is designed to work efficiently with arrays and is often used in combination with other numpy functions.

Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [13]:
print("list_ : ")
for i in list_:
  print(type(i))

print()

print("array_list_ : ")
for i in array_list:
  print(type(i))

list_ : 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

array_list_ : 
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

There will be no change in the data type of the elements present in variable list_.

The elements in array_list will be changed to numpy.int_64 data type

In [17]:
array_list = np.array(object = list_, dtype = int)
print("list_ : ")
for i in list_:
  print(type(i))

print()

print("array_list_ : ")
for i in array_list:
  print(type(i))

list_ : 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

array_list_ : 
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [18]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [19]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [22]:
np.random.randint(0,1, (3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
# or
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# or
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])